cuvant1=str(input("Dati un cuvant: "))
cuvant2=str(input("Dati al doilea cuvant: "))
cuvant3=str(input("Dati al treilea cuvant: "))
cuvant4=str(input("Dati al patrulea cuvant: "))
print(cuvant1)
print(cuvant2)
print(cuvant3)
print(cuvant4)
print('Am participat la olimpiada de %s am luat locul %s apoi mai am olimpiada de %s si sper ca ma voi %s.' % (cuvant1,cuvant2,cuvant3,cuvant4))